// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGaHvbesKuF2jps4ANQGvGfaTXPmZ1T4g',
    appId: '1:1046419452826:web:f2bd264e20d8fac68ec023',
    messagingSenderId: '1046419452826',
    projectId: 'dacs-ban-xe',
    authDomain: 'dacs-ban-xe.firebaseapp.com',
    storageBucket: 'dacs-ban-xe.firebasestorage.app',
    measurementId: 'G-NFSG0LFS5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGtd09FNoHoKJMB-QG76yoiDBw0iLN0hE',
    appId: '1:1046419452826:android:c7340b1a1d7b26948ec023',
    messagingSenderId: '1046419452826',
    projectId: 'dacs-ban-xe',
    storageBucket: 'dacs-ban-xe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCX9Ec8PGoarr7LnuSvCOBmSE5jt2RpOM',
    appId: '1:1046419452826:ios:c65aee3e74354ee18ec023',
    messagingSenderId: '1046419452826',
    projectId: 'dacs-ban-xe',
    storageBucket: 'dacs-ban-xe.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCX9Ec8PGoarr7LnuSvCOBmSE5jt2RpOM',
    appId: '1:1046419452826:ios:c65aee3e74354ee18ec023',
    messagingSenderId: '1046419452826',
    projectId: 'dacs-ban-xe',
    storageBucket: 'dacs-ban-xe.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGaHvbesKuF2jps4ANQGvGfaTXPmZ1T4g',
    appId: '1:1046419452826:web:3837cb407e007fda8ec023',
    messagingSenderId: '1046419452826',
    projectId: 'dacs-ban-xe',
    authDomain: 'dacs-ban-xe.firebaseapp.com',
    storageBucket: 'dacs-ban-xe.firebasestorage.app',
    measurementId: 'G-8HYG1HRF1V',
  );
}
